// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['backend']['App']['CheckUpdate']();
}

export function GetConfig() {
  return window['go']['backend']['App']['GetConfig']();
}

export function GetDashboard(arg1) {
  return window['go']['backend']['App']['GetDashboard'](arg1);
}

export function GetVersion() {
  return window['go']['backend']['App']['GetVersion']();
}

export function ImportKeyDetail(arg1) {
  return window['go']['backend']['App']['ImportKeyDetail'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['backend']['App']['SaveConfig'](arg1);
}

export function SendSubscription(arg1) {
  return window['go']['backend']['App']['SendSubscription'](arg1);
}

export function SetAutoRefresh(arg1) {
  return window['go']['backend']['App']['SetAutoRefresh'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['backend']['App']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['backend']['App']['Startup'](arg1);
}

export function UpdateToken(arg1) {
  return window['go']['backend']['App']['UpdateToken'](arg1);
}
