// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CheckUpdate():Promise<any>;

export function GetConfig():Promise<Record<string, any>>;

export function GetDashboard(arg1:string):Promise<any>;

export function GetVersion():Promise<string>;

export function ImportKeyDetail(arg1:string):Promise<any>;

export function SaveConfig(arg1:Record<string, any>):Promise<void>;

export function SendSubscription(arg1:string):Promise<void>;

export function SetAutoRefresh(arg1:number):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateToken(arg1:string):Promise<void>;
